Swal.fire({
	// title:
	// text:
	// html:
	// icon:
	// confirmButtonText:
	// footer:
	// width:
	// padding:
	// background:
	// grow:
	backdrop: false,
	// timer:
	timerProgressBar: 3000,
	toast: true,
	position: "bottom-end",
	allowOutsideClick: true,
	allowEscapeKey: true,
	allowEnterKey: true,
	stopKeydownPropagation: false,
	// input:
	// inputPlaceholder:
	// inputValue:
	// inputOptions:
	//  customClass:
	// 	container:
	// 	popup:
	// 	header:
	// 	title:
	// 	closeButton:
	// 	icon:
	// 	image:
	// 	content:
	// 	input:
	// 	actions:
	// 	confirmButton:
	// 	cancelButton:
	// 	footer:
	// showConfirmButton:
	// confirmButtonColor:
	// confirmButtonAriaLabel:
	// showCancelButton:
	// cancelButtonText:
	// cancelButtonColor:
	// cancelButtonAriaLabel:
	// buttonsStyling:
	// showCloseButton:
	// closeButtonAriaLabel:
	// imageUrl:
	// imageWidth:
	// imageHeight:
	// imageAlt:
});
