let stockProductos = [
	{
		id: 1,
		nombre: "Nike AirMax",
		tipo: "teclado",
		cantidad: 1,
		desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
		precio: 1200,
		img: "../../img/img1.jpg",
	},
	{
		id: 2,
		nombre: "Nike AirMax",
		tipo: "auriculares",
		cantidad: 1,
		desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
		precio: 1100,
		img: "../img/img2.jpg",
	},
	{
		id: 3,
		nombre: "Nike AirMax",
		tipo: "teclado",
		cantidad: 1,
		desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
		precio: 1200,
		img: "../img/img3.jpg",
	},
	{
		id: 4,
		nombre: "Nike AirMax",
		tipo: "monitor",
		cantidad: 1,
		desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
		precio: 500,
		img: "../img/img5.jpg",
	},
];
