let stockProductos = [
	{
		id: 1,
		nombre: "Buzo 1",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1200,
		talle: "L",
		img: "./img/buzo.jpg",
	},
	{
		id: 2,
		nombre: "Buzo 2",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1100,
		talle: "L",
		img: "./img/buzo.jpg",
	},
	{
		id: 3,
		nombre: "Buzo 3",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1200,
		talle: "M",
		img: "./img/buzo.jpg",
	},
	{
		id: 4,
		nombre: "Buzo 4",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1400,
		talle: "M",
		img: "./img/buzo.jpg",
	},
	{
		id: 5,
		nombre: "Buzo 5",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1200,
		talle: "S",
		img: "./img/buzo.jpg",
	},
	{
		id: 6,
		nombre: "Buzo 6",
		tipo: "buzo",
		cantidad: 1,
		desc: "Un buzo que re va con vos",
		precio: 1500,
		talle: "S",
		img: "./img/buzo.jpg",
	},
	{
		id: 7,
		nombre: "Remera 1",
		tipo: "remera",
		cantidad: 1,
		desc: "Una remera que re va con vos",
		precio: 500,
		talle: "L",
		img: "./img/remera.jpg",
	},
	{
		id: 8,
		nombre: "Remera 2",
		tipo: "remera",
		cantidad: 1,
		desc: "Una remera que re va con vos",
		precio: 500,
		talle: "L",
		img: "./img/remera.jpg",
	},
];
